### ISSUE TITLE
PhishingQuiz

### ISSUE THREAD

**Issue by lenfra** [OpenSecEd/auth#19]
Interesting?
https://phishingquiz.withgoogle.com

**Comment by dbosk** [comment]
We can probably use it. It illustrates the problem of machine--user 
authentication (is machine lying or not) nicely. So it's a good start 
for discussing how to solve the problem (which is the direction I want 
to change the labs to, see #11, #7).

**Comment by dbosk** [comment]
Included the URL in the [slides on usability](https://github.com/OpenSecEd/usability) (`attacking-humans`), suggested students to try it.
